apiVersion: v1
kind: Service
metadata:
  name: kie
  labels:
    app: kie
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30082
  selector:
    app: kie
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kie
spec:
  selector:
    matchLabels:
      app: kie
  replicas: 1
  template:
    metadata:
      labels:
        app: kie
    spec:
      containers:
      - name: kie
        image: 10.240.255.5:5000/jboss/kie-server-roadmap.7.6.0.final:v0.1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
          - name: KIE_WB_PORT
            value: "8080"
          - name: KIE_WB_ADDR
            value: "drools"
