apiVersion: v1
kind: Service
metadata:
  name: flow-frontend
  labels:
    app: flowmanager
    tier: frontend
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - name: http
    port: 3001
    nodePort: 31111
  selector:
    app: flowmanager
    tier: frontend
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: flow-frontend
spec:
  selector:
    matchLabels:
      app: flowmanager
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: flowmanager
        tier: frontend
    spec:
      containers:
      - name: flowui
        image: 10.240.255.5:5000/flowui:v3
        ports:
        - containerPort: 3001
